language: python

python:
  - "3.4"

cache: pip

install:
  - pip install -r test_requirements.txt
  - pip install -e .
  - travis_wait 30 mvn install 

script: 
  - pytest

branches:
  only:
    - master
