language: python

python:
  - "3.4"

cache: pip

before_install:
  - sudo apt-get -qq install ghostscript
  - sudo apt-get -qq install dvipng
  - sudo apt-get update
  - sudo apt-get install mafft
  - sudo apt-get install raxml

install:
  - pip install -r test_requirements.txt
  - pip install -e .

script:
  - pytest

branches:
  only:
    - master

notifications:
  email:
    - skhilton@uw.edu
    - jbloom@fredhutch.org
